version: '3'
services:  
  # Master & Slave
  master:
    image: "redis:latest"
    hostname: master    
    command: redis-server 
  slave:
    image: "redis:latest"    
    hostname: slave    
    command: redis-server --slaveof master 6379   
  # Sentinel
  sentinel:
    build: .
    hostname: sentinel    
    links:
      - master
      - slave